hazelcast/hazelcast-jet-ansible-tests

large-snapshot-chunk-test/src/main/java/com/hazelcast/jet/tests/largesnapshotchunk/LargeSnapshotChunkProducer.java, large-snapshot-chunk-test/src/main/java/com/hazelcast/jet/tests/largesnapshotchunk/LargeSnapshotChunkTest.java, large-snapshot-chunk-test/src/main/java/com/hazelcast/jet/tests/largesnapshotchunk/VerificationProcessor.java
The previous version didn't actually produce large snapshot chunks (it
stored frames of 1kB). Also produce large data only to 1st partition.
=> Fix LargeSnapshotChunkTest

hdfs-test/src/main/java/com/hazelcast/jet/tests/hdfs/HdfsWordCountTest.java
`verify()` method uses assertions to check results but `AssertionError` is `Throwable` not `Exception`. It means that `exception` is not set even if there is any assertion error in test. It can cause that test will looks like passed even if there was any failure.
=> Fixed catch in HdfsWordCountTest

cooperative-map-cache-source-test/pom.xml, cooperative-map-cache-source-test/src/main/java/com/hazelcast/jet/tests/cooperativesource/CooperativeMapCacheSourceTest.java, pom.xml
Added soak tests for sources which uses:
* local Map
* local Cache
* remote Map
* remote Cache
* querying in local Map
* querying in remote Map
Based on TS design, all of these tests are executed in one test case `CooperativeMapCacheSourceTest`.
=> Added test for Cooperative Map & Cache Sources

pom.xml, s3-test/pom.xml, s3-test/src/main/java/com/hazelcast/jet/test/s3/S3WordCountTest.java, s3-test/src/main/java/com/hazelcast/jet/test/s3/WordGenerator.java
added a word-count test which reads from an S3 bucket and writes the results to the same bucket in a folder. source files are generated at the beginning of the test
see https://github.com/hazelcast/hazelcast-jet-ansible/pull/14
=> Add s3 soak test

early-results-test/src/main/java/com/hazelcast/jet/tests/earlyresults/EarlyResultsTest.java
- log warning if no early result emitted
- check for re-ordering of results
=> Early result test fix

async-transform-test/pom.xml, async-transform-test/src/main/java/com/hazelcast/jet/tests/async/AsyncTransformTest.java, cooperative-map-cache-source-test/pom.xml, early-results-test/pom.xml, early-results-test/src/main/java/com/hazelcast/jet/tests/earlyresults/EarlyResultsTest.java, event-journal-test/pom.xml, hdfs-test/pom.xml, jdbc-test/pom.xml, jms-test/pom.xml, job-management-test/pom.xml, job-management-test/src/main/java/com/hazelcast/jet/tests/management/VerificationProcessor.java, kafka-session-window-test/pom.xml, large-snapshot-chunk-test/pom.xml, pom.xml, remote-controller-client/pom.xml, rolling-aggregate-test/pom.xml, s3-test/pom.xml, s3-test/src/main/java/com/hazelcast/jet/tests/s3/S3WordCountTest.java, snapshot-test/pom.xml, snapshot-test/src/main/java/com/hazelcast/jet/tests/snapshot/SnapshotTest.java, snapshot-test/src/main/java/com/hazelcast/jet/tests/snapshot/SnapshotTradeProducer.java, soak-tests-common/pom.xml, soak-tests-common/src/main/java/com/hazelcast/jet/tests/common/Util.java, stateful-map-test/pom.xml, stateful-map-test/src/main/java/com/hazelcast/jet/tests/stateful/StatefulMapTest.java, stateful-map-test/src/main/java/com/hazelcast/jet/tests/stateful/TransactionGenerator.java, stateful-map-test/src/main/java/com/hazelcast/jet/tests/stateful/VerificationEntryProcessor.java
fix npe while cluster is shutting down
Log Exception for stable cluster even if dynamic test failed for stateful mapping
configure sink maps with hot restart
fix map name
log exception when it happens
remove pending logic
Fixed checkstyle error
change to deterministic ts
change ttl to event time
Fixed checkstyles
temp added logging to Util
Update cancelJobAndJoin
Cleanup in Util.cancelJobAndJoin
Updated timeout for S3Client
set socket timeout for client
Count socket timeout number and assert that it happens once in an hour (#28)
* count socket timeout number and assert that it happens once in an hour
* handle undefined-error-code for client
use stable cluster as a sink for stateful-map-test
fix sink map names
Added workaround in cancelJobAndJoin
Added checking of SocketException in S3 …
=> Changes during 3.2 release

jms-test/src/main/java/com/hazelcast/jet/tests/jms/JmsTest.java, snapshot-kafka-test/src/main/java/com/hazelcast/jet/tests/snapshot/kafka/SnapshotKafkaTest.java, soak-tests-common/src/main/java/com/hazelcast/jet/tests/common/AbstractSoakTest.java
- Move the test to dynamic cluster
- Configure the test with EXACTLY_ONCE processing guarantee
- Submit the job to stable cluster also
1 hour run passed 
http://jenkins.hazelcast.com/job/jet-soak-tests/129/
=> 2pc jms test

job-management-test/src/main/java/com/hazelcast/jet/tests/management/VerificationProcessor.java
The scenario:
job is processing the odd values 
export snapshot called -> counter: 5 priorityQueue: 7, 9.
job is now processing the even values
restoreFromSnapshot increments the counter to 6 and clears the queue, the next even item is 10, 6 is filtered out by previous job.
With the change we first check if `restoreFromSnapshot` is called for a switch between old/even values, if so we use the largest value in the queue to set the verification counter.
=> While switching from odds to evens use the largest value in the queue to start the counter

early-results-test/src/main/java/com/hazelcast/jet/tests/earlyresults/EarlyResultsTest.java
Add logging instead of assertion 
In its current state, when the assertion fails, the job stops and we do not have an idea about the future results. I removed the assertion and add logging there to understand more about the cause of failure.
=> Add Logging to EarlyResultsTest

early-results-test/src/main/java/com/hazelcast/jet/tests/earlyresults/EarlyResultsTest.java
- fails the test if receives a result for previous window
- fails the test if receives a final result for next window, does not fail if it is an early result.
=> Rewrite early-result-test verification according to ordering contract

jms-test/src/main/java/com/hazelcast/jet/tests/jms/JmsTest.java, snapshot-jms-source-test/src/main/java/com/hazelcast/jet/tests/snapshot/jmssource/JmsSourceTest.java, stateful-map-test/src/main/java/com/hazelcast/jet/tests/stateful/StatefulMapTest.java
Producers in some tests which run on both clusters were not stopped if the test failed only on one of clusters.
=> Stop producers if tests fail

cdc-source-test/src/main/java/com/hazelcast/jet/tests/cdc/source/VerificationProcessor.java, job-management-test/src/main/java/com/hazelcast/jet/tests/management/JobManagementTest.java, job-management-test/src/main/java/com/hazelcast/jet/tests/management/VerificationProcessor.java, snapshot-jms-source-test/src/main/java/com/hazelcast/jet/tests/snapshot/jmssource/VerificationProcessor.java
cdc-source verification processor was not removing the duplicate
key from the priority-queue. Also use `map.setAsync` instead of
`map.put` since it can fail with instance not active exception.
use `map.setAsync` instead of `map.put` for snapshot-jms-source-test
since it can fail with instance not active exception.
use SinkType.TOTAL_PARALLELISM_ONE for job-management sink
and get rid off manually grouping items to a single constant
key in the pipeline
=> Fix verification for cdc-source-test/snapshot-jms-source-test

soak-tests-common/src/main/java/com/hazelcast/jet/tests/common/AbstractSoakTest.java
The reasoning:
We have a failure in `snapshot-kafka-test`, sometimes at the beginning of the test we get dropped events. When I checked the logs from successful runs and failed runs, we get this loggin in failed ones `Unable to get partition metadata...`. This is logged when kafka processor tries to get the partition count for a topic. If the topic is not yet created, you get a timeout exception. By adding some delay between init and test, we try to ensure the topic is created when processor starts running.
=> Introduce delay(15s) after init to ensure the resources created before starting the test

attach-ml-model-test/src/main/java/com/hazelcast/jet/tests/attachml/AttachMLModelTest.java, cooperative-map-cache-source-test/src/main/java/com/hazelcast/jet/tests/cooperativesource/CooperativeMapCacheSourceTest.java, hdfs-test/src/main/java/com/hazelcast/jet/tests/hdfs/HdfsWordCountTest.java, light-jobs-test/src/main/java/com/hazelcast/jet/tests/lightjobs/LightJobsTest.java, missing-permission-test/src/main/java/com/hazelcast/jet/tests/permissions/MissingPermissionTest.java
Because the light jobs speed up job submission also for regular jobs
this commit increases the time between 2 job submissions from 100 to
1000 ms. This makes the jobs submit at roughly same rate as before the
light jobs commit.
=> Increase sleep between jobs from 100 to 1000 ms

elastic-test/src/main/java/com/hazelcast/jet/tests/elastic/ElasticTest.java
Soak test failed with `java.net.ConnectException: Timeout connecting to [/10.0.0.81:9200]` during `deleteIndex` - this PR adds retry to that method + just log if it failed and not fail the whole test.
=> Improve deleteIndex in elastic test

remote-controller-client/src/main/java/com/hazelcast/jet/tests/remote/RemoteControllerClient.java
This PR:
- fix full restart in HZ 5.x dynamic cluster jet soak tests
- wait for member start/stop in remote controller client (as was originally implemented in https://github.com/hazelcast/hazelcast-jet-ansible-tests/pull/96)
=> Fix full restart in dynamic cluster

cdc-sink-test/src/main/java/com/hazelcast/jet/tests/cdc/sink/CdcSinkTest.java, jdbc-test/pom.xml, snapshot-jdbc-test/pom.xml
The recordPart suppliers should never return null; instead, supplier may be null.
=> ChangeRecord nullability fix

elastic-test/src/main/java/com/hazelcast/jet/tests/elastic/ElasticTest.java
ElasticTest failed due to timeout in connection to elastic but retry mechanism was implemented only for IOException. Following exception was thrown on client side:
```
ElasticsearchException[java.util.concurrent.ExecutionException: java.net.ConnectException: Timeout connecting to [/10.0.0.180:9200]]; nested: ExecutionException[java.net.ConnectException: Timeout connecting to [/10.0.0.180:9200]]; nested: ConnectException[Timeout connecting to [/10.0.0.180:9200]];
at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2695)
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171)
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137)
at …
```
=> Retry for timeout for deleting index in ElasticTest

kafka-session-window-test/src/main/java/com/hazelcast/jet/tests/kafka/KafkaSessionWindowTest.java, snapshot-kafka-test/src/main/java/com/hazelcast/jet/tests/snapshot/kafka/SnapshotKafkaTest.java, soak-tests-common/src/main/java/com/hazelcast/jet/tests/common/QueueVerifier.java, stateful-map-test/src/main/java/com/hazelcast/jet/tests/stateful/KafkaSinkVerifier.java, stateful-map-test/src/main/java/com/hazelcast/jet/tests/stateful/KafkaTradeProducer.java, stateful-map-test/src/main/java/com/hazelcast/jet/tests/stateful/StatefulMapTest.java
Example job - https://jenkins.hazelcast.com/view/Jet%20-%20Misc/job/jet-soak-tests-ondrej/229/console 
Tested with `5.5.0-DEVEL-5` but it's the same as master. Only unrelated python tests is failing. I also tried to run it with `5.5.0-DEVEL-5` before kafka related changes in `hazelcast-jet-ansible` (i.e. when kafka is down) and all 3 tests failed (expected behavior.)
=> Fix kafka tests

cdc-sink-test/pom.xml, cdc-sink-test/src/main/java/com/hazelcast/jet/tests/cdc/sink/CdcSinkTest.java, cdc-source-test/pom.xml, cdc-source-test/src/main/java/com/hazelcast/jet/tests/cdc/source/CdcSourceTest.java
hazelcast-jet-ansible PR: https://github.com/hazelcast/hazelcast-jet-ansible/pull/141
Jenkins job: https://jenkins.hazelcast.com/view/Jet%20-%20Misc/job/jet-soak-tests-ondrej/290/console
- 15hours soak test passed
- `isolated-jobs-stream-test.log isolated-jobs-batch-test.log` failed due to the license and it's not related to this PR
- it was executed with `.setProperty("database.server.id", clusterName.contains(STABLE_CLUSTER) ? 444444 : 555555)` since there was issue in the connector with `setDatabaseClientId`. However it's already fixed hence `.setDatabaseClientId(clusterName.contains(STABLE_CLUSTER) ? 444444 : 555555)` is used in this PR.
=> [DEX-270] Use HZ EE connector for CDC tests

pom.xml, subset-routing-test/pom.xml
I've included both dependencies of `hazelcast-enterprise` and `hazelcast-enterprise-java-client` in one project but final tests-jars are created with proper dependencies.
Ansible PR: https://github.com/hazelcast/hazelcast-jet-ansible/pull/145
Run: https://jenkins.hazelcast.com/job/jet-soak-tests-standalone/34/console
Note: Shown as failed because I forgot to change the final check if something was failed.
=> Include hazelcast java client standalone in the tests
